name: Change Meross Lamp Color

on:
  schedule:
    # Green at 6:45 AEST / 7:45 AEDT, change this when daylight savings changes  
    - cron: "45 20 * * *" # 6:45 AEST (UTC+10)
    # Yellow at 10:00 / 11 AM AEDT, change this when daylight savings changes
    - cron: "0 0 * * *" # 10:00 AEST (UTC+10)
  workflow_dispatch:
    inputs:
      color:
        description: "Choose lamp color"
        required: true
        type: choice
        options:
          - green
          - yellow

jobs:
  change-color:
    runs-on: ubuntu-latest

    steps:
      - name: Debug GitHub Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Scheduled Event: ${{ github.event.schedule }}"
          echo "Manual Color Input: ${{ inputs.color }}"

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Change color to green (Scheduled local 6:45)
        if: github.event_name == 'schedule' && startsWith(github.event.schedule, '45 ')
        env:
          MEROSS_EMAIL: ${{ secrets.MEROSS_EMAIL }}
          MEROSS_PASSWORD: ${{ secrets.MEROSS_PASSWORD }}
          DEVICE_UUID: ${{ secrets.DEVICE_UUID }}
        run: |
          source venv/bin/activate
          python meross_lamp.py --set-colour green

      - name: Change color to yellow (Scheduled local 10:00)
        if: github.event_name == 'schedule' && startsWith(github.event.schedule, '0 ')
        env:
          MEROSS_EMAIL: ${{ secrets.MEROSS_EMAIL }}
          MEROSS_PASSWORD: ${{ secrets.MEROSS_PASSWORD }}
          DEVICE_UUID: ${{ secrets.DEVICE_UUID }}
        run: |
          source venv/bin/activate
          python meross_lamp.py --set-colour yellow

      - name: Change color manually
        if: github.event_name == 'workflow_dispatch'
        env:
          MEROSS_EMAIL: ${{ secrets.MEROSS_EMAIL }}
          MEROSS_PASSWORD: ${{ secrets.MEROSS_PASSWORD }}
          DEVICE_UUID: ${{ secrets.DEVICE_UUID }}
        run: |
          source venv/bin/activate
          python meross_lamp.py --set-colour ${{ inputs.color }}

      - name: Debug Workflow Completion
        if: always()
        run: |
          echo "Workflow completed"
          echo "Status: ${{ job.status }}"
