name: Change Meross lamp colour schedule

on:
  # Run hourly at minute 45 UTC; workflow_dispatch allows manual runs
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:
    inputs:
      time:
        description: 'Override local time (HH:MM) for testing'
        required: false
      color:
        description: 'Override colour for manual run (green or yellow)'
        required: false
        type: choice
        options:
          - green
          - yellow

jobs:
  change-lamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine local time and set colour
        shell: bash
        env:
          # Allow manual override of time or color for testing
          TIME_OVERRIDE:  ${{ github.event.inputs.time }}
          COLOR_OVERRIDE: ${{ github.event.inputs.color }}
          MEROSS_EMAIL:    ${{ secrets.MEROSS_EMAIL }}
          MEROSS_PASSWORD: ${{ secrets.MEROSS_PASSWORD }}
          DEVICE_UUID:     ${{ secrets.DEVICE_UUID }}
        run: |
          # If a colour override is provided in a manual dispatch, use it directly
          if [ -n "$COLOR_OVERRIDE" ]; then
            COLOR="$COLOR_OVERRIDE"
            echo "::notice::Manual override colour: $COLOR"
          else
            # Determine the time to use (manual override or actual local)
            if [ -n "$TIME_OVERRIDE" ]; then
              NOW="$TIME_OVERRIDE"
            else
              NOW=$(TZ=Australia/Sydney date +'%H:%M')
            fi
            echo "Local (Canberra) time is $NOW"
            case "$NOW" in
              "06:45") COLOR=green ;;    # morning: green
              "10:45") COLOR=yellow ;;   # 4h later: yellow
              *) echo "::notice::Not a target time—exiting."; exit 0 ;;
            esac
            echo "::notice::Selected scheduled colour: $COLOR"
          fi
          python meross_lamp.py --set-colour $COLOR